### ISSUE TITLE
Expand dataflows cookbook

### ISSUE THREAD

**Issue by sglavoie** [datahq/dataflows#135]
*Created by @zelima*

As a dataflows user, I want some tutorials/examples of how to do X,Y,Z in dataflows (Eg: scraping), so that can easily understand how to use and start using it

As a dataflows user I want some examples of how to use dataflows with various python packages like Ipython, Pandas etc... so that I have more tools

## Acceptance Criteria

* [ ] We have examples/tutorials
* [ ] Tutorials reviewed by somebody who does not know dataflows

## Tasks

* [ ] List what can be done by dataflows
  * [ ] Write post how those thing can be done
* [ ] Come up with examples using dataflows with Ipython 
  * [ ] Write a post/tutorial
* [ ] Come up with examples using dataflows with Pandas 
  * [ ] Write a post/tutorial
* [ ] Let somebody review it
* [ ] publish
